function generate(startingPosition: string) : string {
    return `........
            ...**...
            ...**...
            ........`;
}

describe('GameOfLife - Acceptance tests', () => {
   
    it('Generation 1 -> Generation 2', () => {
       let startingPosition = 
           `........
            ....*...
            ...**...
            ........`
       let outputPosition = 
           `........
            ...**...
            ...**...
            ........`;
       let nextPosition = generate(startingPosition);
       expect(nextPosition).toBe(outputPosition);
   }) 
});