import {generate} from "../src/gameOfLife";

describe('GameOfLife - Acceptance tests', () => {
   
    it('Generation 1 -> Generation 2', () => {
        const startingPosition =
            `........
            ....*...
            ...**...
            ........`;
        const outputPosition =
            `........
            ...**...
            ...**...
            ........`;
        const nextPosition = generate(startingPosition);
        expect(nextPosition).toBe(outputPosition);
   }) 
});